---
title: "BaseballPitches"
author: "Dan Murphy"
date: "10/23/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r loadData}
atbats <- read.csv(file="/Users/danielmurph8/Desktop/atbats.csv", header= TRUE, sep = ",")
```

Below, I will display the head and tail of our dataset, the column names, and number of rows and columns.
```{r displayData}
dataHead <- head(atbats, n = 15)
dataHead
dataTail <- tail(atbats, n = 15)
dataTail

colnames(atbats)
nrow(atbats)
ncol(atbats)
```
Now, I want to create a bar chart for different event type occurences. 
```{r uniqueValues}
singleCount = 0
doubleCount = 0
tripleCount = 0
homerCount = 0
unique(atbats$event)
for (val in atbats$event){
  if (val == "Single"){
    singleCount = singleCount+1
  }
  else if (val == "Double"){
    doubleCount = doubleCount + 1
  }
  else if (val == "Triple"){
    tripleCount = tripleCount + 1
  }
  else if (val == "Home Run") {
    homerCount = homerCount + 1
  }
}
xLab <- c("Single", "Double", "Triple", "Homerun")
totalHits <- c(singleCount, doubleCount, tripleCount, homerCount)
minData <- min(totalHits)
maxData <- max(totalHits)
barColors <- c("lightblue", "lightgreen", "darkred", "lightyellow")
tickMarks <- (maxData - minData)/10


barplot(totalHits, names.arg = xLab, xlab = "Hit Type", ylab = "Total Hit Count (2015-2018)", main = "Hit Counts between 2015 and 2018", col = barColors, border="grey", yaxt = 'n')
axis(2, at = c(minData - tickMarks*1, minData, minData + tickMarks*1, minData + tickMarks*2, minData + tickMarks*3, minData + tickMarks*4, minData + tickMarks*5, minData + tickMarks*6, minData + tickMarks*7, minData + tickMarks*8, minData + tickMarks*9, minData + tickMarks*10, minData + tickMarks*11), labels = c(minData - tickMarks*1, minData, minData + tickMarks*1, minData + tickMarks*2, minData + tickMarks*3, minData + tickMarks*4, minData + tickMarks*5, minData + tickMarks*6, minData + tickMarks*7, minData + tickMarks*8, minData + tickMarks*9, minData + tickMarks*10, minData + tickMarks*11), 
text.default(x = c(.7, 1.9, 3.1, 4.3), y = c(15000, 15000, 15000, 15000), labels = c(singleCount, doubleCount, tripleCount, homerCount)), )

```

Using the same data to build a differently-colored bar chart. 
```{r newColors}
barplot(totalHits, names.arg = xLab, xlab = "Hit Type", ylab = "Total Hit Count (2015-2018)", main = "Hit Counts between 2015 and 2018", density = c(40, 40, 40, 40), angle = c(0, 45, 90, 17, 36), col = c("coral4", "cornflowerblue", "cyan4", "darkgoldenrod3"), yaxt = "n")

axis(2, at = c(minData - tickMarks*1, minData, minData + tickMarks*1, minData + tickMarks*2, minData + tickMarks*3, minData + tickMarks*4, minData + tickMarks*5, minData + tickMarks*6, minData + tickMarks*7, minData + tickMarks*8, minData + tickMarks*9, minData + tickMarks*10, minData + tickMarks*11), labels = c(minData - tickMarks*1, minData, minData + tickMarks*1, minData + tickMarks*2, minData + tickMarks*3, minData + tickMarks*4, minData + tickMarks*5, minData + tickMarks*6, minData + tickMarks*7, minData + tickMarks*8, minData + tickMarks*9, minData + tickMarks*10, minData + tickMarks*11))

```
Now, I will create a pie chart and 3D-pie chart for hit types.
``` {r pieChart}
pie(totalHits, col = c("darkseagreen", "darkred", "Darkslateblue", "darkslategrey"), labels = c("Singles", "Doubles", "Triples", "Homeruns"))

pie3D(totalHits, col = c("darkseagreen", "skyblue2", "slategray1", "seashell"), labels = c("1B", "2B", "3B", "HR"), explode = 0.075, main = "Pie Chart For Hit Types between 2015- 2018")
```

```{r scatterplot}
scatter <- plot(totalHits, xlab= "Hit Type", ylab = "Total Hit Count (2015-2018)", main = "Hit Counts Between 2015 and 2018", yaxt = 'n', xaxt = 'n', col = "steelblue3", pch = 8, cex = 1.5)

axis(side = 1, at = c(0, 1, 2, 3, 4, 5), labels = c("", "Single", "Double", "Triple", "Homerun", ""))
axis(side = 2, at = c(minData - tickMarks*1, minData, minData + tickMarks*1, minData + tickMarks*2, minData + tickMarks*3, minData + tickMarks*4, minData + tickMarks*5, minData + tickMarks*6, minData + tickMarks*7, minData + tickMarks*8, minData + tickMarks*9, minData + tickMarks*10, minData + tickMarks*11), labels = c(minData - tickMarks*1, minData, minData + tickMarks*1, minData + tickMarks*2, minData + tickMarks*3, minData + tickMarks*4, minData + tickMarks*5, minData + tickMarks*6, minData + tickMarks*7, minData + tickMarks*8, minData + tickMarks*9, minData + tickMarks*10, minData + tickMarks*11))

```


```{r donutPlot}
library(ggplot2)
dataDf <- data.frame(
  category = c("Single", "Double", "Triple", "Homer"),
  count = c(singleCount, doubleCount, tripleCount, homerCount)
)


sumCount <- singleCount+doubleCount+tripleCount+homerCount
singleFrac <- singleCount/sumCount
doubleFrac <- doubleCount/sumCount
tripleFrac <- tripleCount/sumCount
homerFrac <- homerCount/sumCount

#verify sumCount is correct number
sumCount == sum(singleCount, doubleCount, tripleCount, homerCount)

#now, assign fractions to list
dataFrac <- c(singleFrac, doubleFrac, tripleFrac, homerFrac)
dataYMax <- cumsum(dataFrac)
dataYMin <- c(0, head(dataYMax, n=-1))

ggplot(hitsDf, aes( ymax = dataYMax, ymin = dataYMin, xmin = 3, xmax = 4)) + geom_rect() + 
  coord_polar(theta = "y") + #set up rectangular coordinates between 0 and 1
  xlim(c(1,4)) + #create donut hole 
  theme_void() + #change theme
  theme(legend.position = "none")
```
